### PR TITLE
Fix typos on comments

### PR DESCRIPTION
**Pull request by altmas5**
Remove consecutive "the" occurrences.
I didn't create a new branch due to the minor changes.

### CODE REVIEW

**Comment by thomasvl** [comment]
All the files in the GeneratedServices directory are just that, so the typos will reappear on the next generation run.

**Comment by altmas5** [comment]
Ok, Shoulld I close the pull request?

**Comment by thomasvl** [comment]
Sorry for the delay, I took a long weekend here.

No need to revert, I'll merge now, just wanted to give the heads up that some things would revert the next time we generated.

**Review by thomasvl — APPROVED** [review]

**Comment by altmas5** [comment]
Ok!

**Pull request merged**
