### PR TITLE
Switches DYLIB_INSTALL_NAME_BASE to @rpath to fix "dyld: Library not …

### PR DESCRIPTION
**Pull request by R4N**
…loaded: @loader_path/Frameworks" when GTLR is embedded in main application and linked in separate framework as referenced in issue #69 (adjusted on GTLRiOS and GTLROSX)

### CODE REVIEW

**Comment by thomasvl** [comment]
fyi - We picked up an updated AppAuth/GTMAppAuth dependency in another CL and we're trying to get travis happy with that (another active PR) before doing yet more build releated changes.

**Comment by thomasvl** [comment]
Told travis to respin, not sure if that will move up to more recent files on not, but hopefully it will and we'll get a better state of things.

**Comment by R4N** [comment]
Cool, thanks for the update.  Let me know if I need to do anything else on my end to have it re-trigger whenever appropriate.

**Comment by thomasvl** [comment]
Looks like it reruns things still based on the state of your branch.  Can you merge/rebase to the the current state of `master` so we can confirm things are good?

**Comment by R4N** [comment]
Should be all set.  Sorry, I should have commented when I merged to catch it up.

**Comment by thomasvl** [comment]
And it looks like travis was happy with it, so thanks!

**Pull request merged**
