### PR TITLE
Generate current service sources and pick up new services.

### PR DESCRIPTION
**Pull request by thomasvl**

### CODE REVIEW

**Comment by 27lahawa29** [comment]
Hi Thomas...

I am not certain I am understanding the attached information I am receiving. In a nut shell can you email me  easy to understand details so I can follow moving forward?

Thank you 

Shelly Forgione

On Jun 16, 2017, at 11:06 AM, Sergio Campamá <notifications@github.com> wrote:

@sergiocampama approved this pull request.

**Comment by thomasvl** [comment]
Looks like you might have set up a watch on this project: https://github.com/google/google-api-objectivec-client-for-rest/watchers

**Comment by 27lahawa29** [comment]
Hi Thomas 

Can you explain sensitive data, ad categories, exchange buyers etc??? I do not understand the reports

Thank you

Shelly Forgione

On Jun 16, 2017, at 11:42 AM, Thomas Van Lenten <notifications@github.com> wrote:

Merged #142.

**Comment by 27lahawa29** [comment]
thank you for getting back to me...I remember signing up for GitHub but
really am an amateur and am not certain what I am opening.  Is there
somewhere I can read up on how to operate and understand watches I have or
wish to set up in future?

Thank you again

2017-06-16 10:28 GMT-04:00 Thomas Van Lenten <notifications@github.com>:

**Pull request merged**
