### PR TITLE
SwiftPM generator changes

### LINKED ISSUE #296: Publish library as a Swift package
Hello,

I want to create an app using this library in Swift, but I want to use the [Swift Package Manager](https://github.com/apple/swift-package-manager/tree/master/Documentation) instead of CocoaPods. This requires the package to have a `Package.swift` file in the root directory as the package specification. It's possible to create a Swift package from Objective C code, so this shouldn't be a problem. 

I have tried to create `Package.swift` myself, but it requires the dependencies like `GTMSessionFetcher` to be published as a Swift Package as well. In addition to this `GoogleSignIn` would need to be published as a Swift Package as well if authorised APIs are used.

Would it be possible to do this?

Thanks!

### PR DESCRIPTION
**Pull request by thomasvl**
Fixes #296

### CODE REVIEW

**Comment by thomasvl** [comment]
@karimhm fyi.

**Comment by thomasvl** [comment]
Using a sub package for the ServiceGenerator seemed better since the it otherwise could risk collisions on in the module namespace if something tried to depend on the main Package file and something else had a transitive name of "ServiceGenerator" (and I didn't want to prefix it with the package making it really long also).

**Comment by karimhm** [comment]
@thomasvl Where the `GTLR_USE_MODULAR_IMPORT` flag get defined?

**Comment by thomasvl** [comment]
> Where the `GTLR_USE_MODULAR_IMPORT` flag get defined?

It isn't, it is a back door for someone that needs modular imports they can define it in their Xcode project file.

The normal swiftpm build works just be the gate on `SWIFT_PACKAGE`.

**Comment by karimhm** [comment]
> > Where the `GTLR_USE_MODULAR_IMPORT` flag get defined?
> 
> It isn't, it is a back door for someone that needs modular imports they can define it in their Xcode project file.
> 
> The normal swiftpm build works just be the gate on `SWIFT_PACKAGE`.

I see. Nice trick!

**Pull request merged**
